FROM rust:latest

RUN apt-get update && apt-get install -y git

WORKDIR /usr/src/dwarf

RUN git clone https://github.com/uberfoo/sarzak-cli
RUN git clone https://github.com/uberfoo/dwarf

RUN cd sarzak-cli && cargo install --path .
RUN cd dwarf && cargo xtask install && cargo xtask plugin

ENTRYPOINT ["dwarf"]
