//! Foo Domain
//!
//! This file was generated by: `sarzak new "foo"`.
use uuid::{uuid, Uuid};

pub mod macros;
pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;
pub use macros::*;

// foo
pub const UUID_NS: Uuid = uuid!("bca95adb-b5f1-564f-96a7-6355c52d1fa7");

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test() {
    }
}
