[book]
authors = ["Keith T. Star"]
language = "en"
multilingual = false
src = "src"
title = "The Dwarf Programming Language"

[output.html]
git-repository-url = "https://github.com/uberfoo/dwarf"
git-repository-icon = "fa-github"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["./mdbook-admonish.css"]

[output.html.code.hidelines]
dwarf = "#"

[output.html.playground]
editable = true
line-numbers = true

[preprocessor.indexing]
[preprocessor.indexing.see_instead]
"equals" = "`==`"
"Let Statement" = "`let`"

[preprocessor.indexing.nest_under]
"`if`" = "expression"
"=" = "expression"
"`==`" = "expression"
"`=`" = "expression"
"`print`" = "expression"
"struct expression" = "expression"

"`let`" = "statement"
"Expression Statement" = "statement"
"Item Statement" = "statement"
"Result Statement" = "statement"
"Let Statement" = "statement"

"`string`" = "types"
"`float`" = "types"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.2" # do not edit: managed by `mdbook-admonish install`
