[modules.lu_dog]
model = "models/lu_dog.json"

[[modules.lu_dog.compiler]]
always_process = true
compiler = "grace"
derive = ["Clone", "Debug", "Deserialize", "PartialEq", "Serialize"]
imported_domains = ["sarzak/v2/sarzak"]
use_paths = ["serde::{Deserialize, Serialize}"]

[modules.lu_dog.compiler.target]
target = "domain"
optimization_level = "None"
is_meta_model = true
is_sarzak = false
persist = true
persist_timestamps = false
uber_store = "StdRwLock"

[[modules.lu_dog.compiler]]
always_process = true
compiler = "grace"

[modules.lu_dog.compiler.target]
target = "dwarf"
is_meta_model = true
is_sarzak = false
uber_store = "StdRwLock"
