#![allow(unreachable_pub)]

xflags::xflags! {
    src "./src/flags.rs"

    /// Run custom build command.
    cmd xtask {
        cmd plugin {
            optional --plugin plugin: String
            optional --debug debug: bool
        }
        cmd package {
            optional --client-patch-version version: String
        }
        cmd install {
            optional --debug debug: bool
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Plugin(Plugin),
    Package(Package),
    Install(Install),
}

#[derive(Debug)]
pub struct Plugin {
    pub plugin: Option<String>,
    pub debug: Option<bool>,
}

#[derive(Debug)]
pub struct Package {
    pub client_patch_version: Option<String>,
}

#[derive(Debug)]
pub struct Install {
    pub debug: Option<bool>,
}

impl Xtask {
    #[allow(dead_code)]
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }

    #[allow(dead_code)]
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    #[allow(dead_code)]
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
