//! Lu Dog Domain
//!
//! This file was generated by: `sarzak new "lu_dog"`.
use uuid::{uuid, Uuid};

pub mod store;
pub mod types;

pub use store::ObjectStore;
pub use types::*;

// lu_dog
pub const UUID_NS: Uuid = uuid!("718a3c7b-8124-5b12-bf4f-6ff6274db22c");

// 🚧 FIxme
pub const MODEL: &[u8] = include_bytes!("../../sarzak/models/lu_dog.v2.json/sarzak.bin");
