name: CI

on:
    workflow_dispatch:
    push:
        branches:
            - develop
            - master
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Checkout sarzak
              uses: actions/checkout@v2
              with:
                  ref: develop
                  path: sarzak
                  repository: 'uberfoo/sarzak'

            - name: Checkout sarzak-cli
              uses: actions/checkout@v2
              with:
                  ref: develop
                  path: sarzak-cli
                  repository: 'uberfoo/sarzak-cli'

            - name: Build sarzak-cli
              run: |
                  cd sarzak-cli
                  cargo install --path .
                  cd ..

            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}
                  path: dwarf

            - name: Remove Sarzak, and the CLI
              run: |
                  rm -rf dwarf/sarzak
                  rm -rf dwarf/sarzak-cli

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Install dwarf
              run: |
                  cd dwarf
                  cargo xtask plugins
                  mkdir -p ~/.dwarf/lib/std
                  cp std/src/* ~/.dwarf/lib/std

            - name: Build and run tests with coverage
              run: |
                  cd dwarf
                  RUST_MIN_STACK=4194304 cargo llvm-cov --lcov --output-path coverage.lcov --no-default-features --features "multi-vec, repl, async"

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              with:
                  working-directory: .
                  fail_ci_if_error: true
                  # files: ./coverage.xml
                  files: coverage.lcov
                  flags: unittests
                  name: codecov-umbrella
                  verbose: true
